In [1]:
import os
from PIL import Image


In [2]:
os.chdir(r"C:\Users\Anand\Desktop\Nft")
def rename_reshape():
    for f in os.listdir():
        img=Image.open(f)
        img=img.resize((300,200),Image.ANTIALAS)
        img.save(str(i).zfill(3)+"jpeg")
        i=i+1

OSError: [Errno 2] No such file or directory: 'C:\\Users\\Anand\\Desktop\\Nft'

In [4]:
import numpy as np

In [6]:
img=Image.open(r"C:\Users\Anand\Desktop\Nft\Test1.jpeg")
x,y = img.size
print(x)
print(y)

1024
812


In [21]:
img=Image.open(r"C:\Users\Anand\Desktop\Nft\Test1.jpeg")
img=img.resize((300,200),Image.ANTIALIAS)
img.save(str(i).zfill(3)+'jpeg',"JPEG")
x,y = img.size
print(x)
print(y)

300
200


In [31]:
os.chdir(r"C:\Users\Anand\Desktop\Nft")
i=1
for f in os.listdir():
    img=Image.open(f)
    img=img.resize((300,200),Image.ANTIALIAS)
    img.save(str(i).zfill(3)+'.jpeg',"JPEG")
    i=i+1

In [84]:
import csv
import os
import pandas as pd
os.chdir(r"C:\Users\Anand\Desktop\Nft")
mydata=list()
for f in os.listdir():
    x,y=os.path.splitext(f)
    if int(x.lstrip('0'))<=5:
        mydata.append([f.strip(),1])
    else:
        mydata.append([f.strip(),-1])
with open("trail.csv","w", newline = '') as myfile:
    wr=csv.writer(myfile)
    wr.writerows(mydata)
df = pd.read_csv(r"C:\Users\Anand\Desktop\Nft\trail.csv", header=None)
df.rename(columns={0: "Image", 1: "label"}, inplace=True)
df.to_csv(r"C:\Users\Anand\Desktop\Nft\Nft__.csv", index=False) # save to new csv file

ValueError: invalid literal for int() with base 10: 'Nft__'

In [8]:
import cv2
from PIL import Image
import numpy as np
img = cv2.imread(r"C:\Users\Anand\Desktop\Nft\001.jpeg", 0)
img2 = Image.open(r"C:\Users\Anand\Desktop\Nft\001.jpeg")

#x,y = img2.size
#print(x)
#print(y)
#for i in range(0,x):
 #   for j in range(0,y):
  #      print(img[i][j])
X = np.array(img)
X = X.flatten()
print(X)
print(X.ndim)
print(X.size)

[ 0  0  1 ... 84 76 73]
1
60000


In [104]:
import cv2
from PIL import Image
import numpy as np
import pandas as pd
import csv
import glob
import os

os.chdir(r"C:\Users\Anand\Desktop\NFT_dataset")

def rename_reshape():
    i=1
    for f in os.listdir():
        img=Image.open(f)
        img=img.resize((300,200),Image.ANTIALIAS)
        img.save(str(i).zfill(3)+'.jpeg',"JPEG")
        i=i+1
        
def create_csv():
    mydata=list()
    for f in os.listdir():
        x,y=os.path.splitext(f)
        if int(x.lstrip('0'))<=5:
            mydata.append([f.strip(),1])
        else:
            mydata.append([f.strip(),-1])
    with open("train_temp.csv","w", newline = '') as myfile:
        wr=csv.writer(myfile)
        wr.writerows(mydata)
    df = pd.read_csv(r"C:\Users\Anand\Desktop\NFT_dataset\train_temp.csv", header=None)
    df.rename(columns={0: "Image", 1: "label"}, inplace=True)
    df.to_csv(r"C:\Users\Anand\Desktop\NFT_dataset\train.csv", index=False) # save to new csv file
    
def create_input_vector():
    inp_X = []
    for img in glob.glob(r"C:\Users\Anand\Desktop\NFT_dataset\*.jpeg"):
        n = cv2.imread(img,0)
        #cv_img.append(n)
        X = np.array(n)
        X = X.flatten()
        X = X[:10]
        print("The image array:")
        print(X)
        inp_X.append(X)
    return inp_X

def create_target_vector():
    colnames = ["Image","label"]
    data = pd.read_csv(r"C:\Users\Anand\Desktop\NFT_dataset\train.csv", names=colnames)
    #images = data.Image.tolist()
    labels = data.label.tolist()
    #images = images[1:]
    labels = labels[1:]
    d = []
    for i in labels:
        d.append(int(i))
    return d
    
class Perceptron(object):
    def __init__(self,input_size,lr,epochs):# Constructor in python
        self.W=np.zeros(input_size+1)# self in python denotes the class atrribute i.e it is data member of the class
        self.lr=lr
        print(self.W)
        self.epochs=epochs
    def activation_fn(self, x):
        if x >= 0:
            return 1
        else:
            return -1
    def predict(self, x):
        #x = np.insert(x, 0, 1)#insert capital B : x has all xi and ,
        z = self.W.T.dot(x)#       Dot product with W i.e weight vectors wi=0 and b=0
        print("The input vector:")
        print(x)
        print("The weight vector:")
        print(self.W)
        print("The dot product of weight vector and input vector:")
        print(z)
        z = np.sum(z)
        print("The final sum:")
        print(z)
        a = self.activation_fn(z)
        return a
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(len(d)):#d is our target vector d.shape[0] tells us the number of rows
                x = np.insert(X[i], 0, 1)#insert capital B : x has all xi and ,
                print("Input array")
                print(x)
                y = self.predict(x)
                e = d[i] - y
                self.W = self.W + self.lr * e * x
                print("The weight vector after updation:")
                print(self.W)
    def testing(self,X,d):
        count = int()
        count = 0
        for i in range(len(d)):#d is our target vector d.shape[0] tells us the number of rows
            x = np.insert(X[i], 0, 1)#insert capital B : x has all xi and ,
            print("Input array")
            print(x)
            y = self.predict(x)
            print("The target",d[i])
            print("The value obtained is",y)
            if y == d[i]:
                count = count + 1
            print("The weight vector after updation:")
            print(self.W)
        return count
        
# def rename_reshape():
    
# def create_csv():
    
# def create_input():
    
# def create_target():
    
if __name__ == '__main__':
    #img = cv2.imread(r"C:\Users\Anand\Desktop\Nft\004.jpeg", 0)
    #img2 = Image.open(r"C:\Users\Anand\Desktop\Nft\001.jpeg")
    #print(img)
#     Y = np.array(img)
#     Y = Y.flatten()
#     Y = Y[:10]
#     print(Y)
    #x,y = img2.size
    #print(x)
    #print(y)
    #for i in range(0,x):
     #   for j in range(0,y):
      #      print(img[i][j])

    #for d in csv.DictReader(open(r"C:\Users\Anand\Desktop\Nft\trail.csv"), delimiter=','):
     #   print(d)
    #"""df = pd.read_csv(r"C:\Users\Anand\Desktop\Nft\Final.csv")
    #images= df["Image"] #you can also use df['column_name']
    #labels=df["label"]
    #print(images)
    #print(labels)"""
#     colnames = ["Image","label"]
#     data = pd.read_csv(r"C:\Users\Anand\Desktop\Nft\Final.csv", names=colnames)
#     images = data.Image.tolist()
#     labels = data.label.tolist()
#     images = images[1:]
#     labels = labels[1:]
   # print(images)
   # print(labels)
#inp_X = []
   #cv_img = []
#     for img in glob.glob(r"C:\Users\Anand\Desktop\Nft\*.jpeg"):
#         n = cv2.imread(img,0)
#         #cv_img.append(n)
#         X = np.array(n)
#         X = X.flatten()
#         X = X[:10]
#         print("The image array:")
#         print(X)
#         inp_X.append(X)
#     for f in os.listdir():
#         img = cv2.imread(f,0);
#         X = np.array(img)
#         X = X.flatten()
#         X = X[:10]
#         print("The image array:")
#         print(X)
#         inp_X.append(X)
#     print(inp_X)
#     print(inp_X[0])
#     inp=[]
#    for i in inp_X:
#         inp.append(i[0].astype('int32'))
#     print(inp)
#     #print(inp_X)
#     #X = np.array(img)
#     #X = X.flatten()
#     #X = X[:10]
#     print(X)
#     print(X.ndim)
#     print(X.size)
#     d = np.array([0])
#     d = []
#     for i in labels:
#         d.append(int(i))
    rename_reshape()
    create_csv()
    inp = create_input_vector()
    size = int()
    size = len(inp)
    t = create_target_vector()
    size = size//4
    size = size*3
    print(size)
    inp_train = inp[:size]
    t_train = t[:size]
    inp_test = inp[size:]
    t_test = t[size:]
    print("Training",inp_train,t_train)
    print("Testing",inp_test,t_test)
    perceptron = Perceptron(inp_train[0].size,0.1,100)
    perceptron.fit(inp_train, t_train)
    print(perceptron.W)
    count = float()
    count=perceptron.testing(inp_test, t_test)
    print("The total count",count)
    accuracy = float()
    accuracy = (count/size)*100
    print("The accuracy is:",accuracy)
#def testing()

The image array:
[ 0  0  1  9 18 26 31 32 38 41]
The image array:
[ 0  0  1  9 18 26 31 32 38 41]
The image array:
[31 31 31 31 31 31 31 31 32 32]
The image array:
[0 0 0 0 0 0 0 0 0 0]
The image array:
[21 21 21 21 21 21 21 21 21 21]
The image array:
[245 245 245 245 245 245 245 245 245 245]
The image array:
[255 247 237 242 254 251 246 255 253 248]
The image array:
[239 251 253 254 255 246 249 255 255 255]
The image array:
[250 250 251 252 252 253 254 254 255 255]
The image array:
[241 242 243 245 247 249 250 251 251 250]
The image array:
[241 242 243 245 247 249 250 251 251 250]
6
Training [array([ 0,  0,  1,  9, 18, 26, 31, 32, 38, 41], dtype=uint8), array([ 0,  0,  1,  9, 18, 26, 31, 32, 38, 41], dtype=uint8), array([31, 31, 31, 31, 31, 31, 31, 31, 32, 32], dtype=uint8), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8), array([21, 21, 21, 21, 21, 21, 21, 21, 21, 21], dtype=uint8), array([245, 245, 245, 245, 245, 245, 245, 245, 245, 245], dtype=uint8)] [1, 1, 1, 1, 1, -1]
Testing

The dot product of weight vector and input vector:
-6051.199999999993
The final sum:
-6051.199999999993
The weight vector after updation:
[  6.8 -65.  -65.  -62.4 -41.6 -18.2   2.6  15.6  18.2  36.4  44.2]
Input array
[1 0 0 0 0 0 0 0 0 0 0]
The input vector:
[1 0 0 0 0 0 0 0 0 0 0]
The weight vector:
[  6.8 -65.  -65.  -62.4 -41.6 -18.2   2.6  15.6  18.2  36.4  44.2]
The dot product of weight vector and input vector:
6.800000000000003
The final sum:
6.800000000000003
The weight vector after updation:
[  6.8 -65.  -65.  -62.4 -41.6 -18.2   2.6  15.6  18.2  36.4  44.2]
Input array
[ 1 21 21 21 21 21 21 21 21 21 21]
The input vector:
[ 1 21 21 21 21 21 21 21 21 21 21]
The weight vector:
[  6.8 -65.  -65.  -62.4 -41.6 -18.2   2.6  15.6  18.2  36.4  44.2]
The dot product of weight vector and input vector:
-2832.3999999999946
The final sum:
-2832.3999999999946
The weight vector after updation:
[  7.  -60.8 -60.8 -58.2 -37.4 -14.    6.8  19.8  22.4  40.6  48.4]
Input array
[  1 245 245 245 2

The input vector:
[ 1 31 31 31 31 31 31 31 31 32 32]
The weight vector:
[  11.4 -103.8 -103.8 -100.2  -71.4  -39.   -10.2    7.8   11.4   37.6
   48.4]
The dot product of weight vector and input vector:
-9921.799999999981
The final sum:
-9921.799999999981
The weight vector after updation:
[ 11.6 -97.6 -97.6 -94.  -65.2 -32.8  -4.   14.   17.6  44.   54.8]
Input array
[1 0 0 0 0 0 0 0 0 0 0]
The input vector:
[1 0 0 0 0 0 0 0 0 0 0]
The weight vector:
[ 11.6 -97.6 -97.6 -94.  -65.2 -32.8  -4.   14.   17.6  44.   54.8]
The dot product of weight vector and input vector:
11.59999999999999
The final sum:
11.59999999999999
The weight vector after updation:
[ 11.6 -97.6 -97.6 -94.  -65.2 -32.8  -4.   14.   17.6  44.   54.8]
Input array
[ 1 21 21 21 21 21 21 21 21 21 21]
The input vector:
[ 1 21 21 21 21 21 21 21 21 21 21]
The weight vector:
[ 11.6 -97.6 -97.6 -94.  -65.2 -32.8  -4.   14.   17.6  44.   54.8]
The dot product of weight vector and input vector:
-5465.199999999988
The final sum:
-

   56.2]
The dot product of weight vector and input vector:
3250.6000000000104
The final sum:
3250.6000000000104
The weight vector after updation:
[  14.8 -106.2 -106.2 -102.4  -72.   -37.8   -7.4   11.6   15.4   44.8
   56.2]
Input array
[ 1 31 31 31 31 31 31 31 31 32 32]
The input vector:
[ 1 31 31 31 31 31 31 31 31 32 32]
The weight vector:
[  14.8 -106.2 -106.2 -102.4  -72.   -37.8   -7.4   11.6   15.4   44.8
   56.2]
The dot product of weight vector and input vector:
-9308.199999999972
The final sum:
-9308.199999999972
The weight vector after updation:
[  15.  -100.  -100.   -96.2  -65.8  -31.6   -1.2   17.8   21.6   51.2
   62.6]
Input array
[1 0 0 0 0 0 0 0 0 0 0]
The input vector:
[1 0 0 0 0 0 0 0 0 0 0]
The weight vector:
[  15.  -100.  -100.   -96.2  -65.8  -31.6   -1.2   17.8   21.6   51.2
   62.6]
The dot product of weight vector and input vector:
14.999999999999979
The final sum:
14.999999999999979
The weight vector after updation:
[  15.  -100.  -100.   -96.2  -65.8  -31.

2794.200000000017
The weight vector after updation:
[  19.6 -116.  -116.  -112.   -80.   -44.   -12.     8.    12.    45.4
   57.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  19.6 -116.  -116.  -112.   -80.   -44.   -12.     8.    12.    45.4
   57.4]
The dot product of weight vector and input vector:
2794.200000000017
The final sum:
2794.200000000017
The weight vector after updation:
[  19.6 -116.  -116.  -112.   -80.   -44.   -12.     8.    12.    45.4
   57.4]
Input array
[ 1 31 31 31 31 31 31 31 31 32 32]
The input vector:
[ 1 31 31 31 31 31 31 31 31 32 32]
The weight vector:
[  19.6 -116.  -116.  -112.   -80.   -44.   -12.     8.    12.    45.4
   57.4]
The dot product of weight vector and input vector:
-10950.799999999957
The final sum:
-10950.799999999957
The weight vector after updation:
[  19.8 -109.8 -109.8 -105.8  -73.8  -37.8   -5.8   14.2   18.2   51.8
   63.8]
Input array
[1 0 0 0 0 0 0 0 0 0 0

Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  24.2 -125.8 -125.8 -121.8  -89.8  -53.8  -21.8   -1.8    2.2   38.4
   50.4]
The dot product of weight vector and input vector:
1099.2000000000237
The final sum:
1099.2000000000237
The weight vector after updation:
[  24.2 -125.8 -125.8 -121.8  -89.8  -53.8  -21.8   -1.8    2.2   38.4
   50.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  24.2 -125.8 -125.8 -121.8  -89.8  -53.8  -21.8   -1.8    2.2   38.4
   50.4]
The dot product of weight vector and input vector:
1099.2000000000237
The final sum:
1099.2000000000237
The weight vector after updation:
[  24.2 -125.8 -125.8 -121.8  -89.8  -53.8  -21.8   -1.8    2.2   38.4
   50.4]
Input array
[ 1 31 31 31 31 31 31 31 31 32 32]
The input vector:
[ 1 31 31 31 31 31 31 31 31 32 32]
The weight vector:
[  24.2 -125.8 -125.8 -121.8  -89.8  -53.8  -21

The final sum:
-61419.3999999995
The weight vector after updation:
[  26.6 -106.2 -106.2 -102.2  -70.2  -34.2   -2.2   17.8   21.8   59.4
   71.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  26.6 -106.2 -106.2 -102.2  -70.2  -34.2   -2.2   17.8   21.8   59.4
   71.4]
The dot product of weight vector and input vector:
5053.800000000027
The final sum:
5053.800000000027
The weight vector after updation:
[  26.6 -106.2 -106.2 -102.2  -70.2  -34.2   -2.2   17.8   21.8   59.4
   71.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  26.6 -106.2 -106.2 -102.2  -70.2  -34.2   -2.2   17.8   21.8   59.4
   71.4]
The dot product of weight vector and input vector:
5053.800000000027
The final sum:
5053.800000000027
The weight vector after updation:
[  26.6 -106.2 -106.2 -102.2  -70.2  -34.2   -2.2   17.8   21.8   59.4
   71.4]
Input array
[ 1 31 31 3

[  1 245 245 245 245 245 245 245 245 245 245]
The weight vector:
[ 29.  -86.6 -86.6 -82.6 -50.6 -14.6  17.4  37.4  41.4  80.4  92.4]
The dot product of weight vector and input vector:
-12710.999999999443
The final sum:
-12710.999999999443
The weight vector after updation:
[ 29.  -86.6 -86.6 -82.6 -50.6 -14.6  17.4  37.4  41.4  80.4  92.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[ 29.  -86.6 -86.6 -82.6 -50.6 -14.6  17.4  37.4  41.4  80.4  92.4]
The dot product of weight vector and input vector:
9008.40000000003
The final sum:
9008.40000000003
The weight vector after updation:
[ 29.  -86.6 -86.6 -82.6 -50.6 -14.6  17.4  37.4  41.4  80.4  92.4]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[ 29.  -86.6 -86.6 -82.6 -50.6 -14.6  17.4  37.4  41.4  80.4  92.4]
The dot product of weight vector and input vector:
9008.40000000003
The final sum:


[  31.  -120.2 -120.2 -116.2  -84.2  -48.2  -16.2    3.8    7.8   48.2
   60.2]
Input array
[  1 245 245 245 245 245 245 245 245 245 245]
The input vector:
[  1 245 245 245 245 245 245 245 245 245 245]
The weight vector:
[  31.  -120.2 -120.2 -116.2  -84.2  -48.2  -16.2    3.8    7.8   48.2
   60.2]
The dot product of weight vector and input vector:
-94342.9999999994
The final sum:
-94342.9999999994
The weight vector after updation:
[  31.  -120.2 -120.2 -116.2  -84.2  -48.2  -16.2    3.8    7.8   48.2
   60.2]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1  0  0  1  9 18 26 31 32 38 41]
The weight vector:
[  31.  -120.2 -120.2 -116.2  -84.2  -48.2  -16.2    3.8    7.8   48.2
   60.2]
The dot product of weight vector and input vector:
2535.400000000035
The final sum:
2535.400000000035
The weight vector after updation:
[  31.  -120.2 -120.2 -116.2  -84.2  -48.2  -16.2    3.8    7.8   48.2
   60.2]
Input array
[ 1  0  0  1  9 18 26 31 32 38 41]
The input vector:
[ 1

[ 35.4 -91.4 -91.4 -87.4 -55.4 -19.4  12.6  32.6  36.6  79.6  91.6]
The dot product of weight vector and input vector:
35.39999999999996
The final sum:
35.39999999999996
The weight vector after updation:
[ 35.4 -91.4 -91.4 -87.4 -55.4 -19.4  12.6  32.6  36.6  79.6  91.6]
Input array
[ 1 21 21 21 21 21 21 21 21 21 21]
The input vector:
[ 1 21 21 21 21 21 21 21 21 21 21]
The weight vector:
[ 35.4 -91.4 -91.4 -87.4 -55.4 -19.4  12.6  32.6  36.6  79.6  91.6]
The dot product of weight vector and input vector:
-1896.5999999999387
The final sum:
-1896.5999999999387
The weight vector after updation:
[ 35.6 -87.2 -87.2 -83.2 -51.2 -15.2  16.8  36.8  40.8  83.8  95.8]
Input array
[  1 245 245 245 245 245 245 245 245 245 245]
The input vector:
[  1 245 245 245 245 245 245 245 245 245 245]
The weight vector:
[ 35.6 -87.2 -87.2 -83.2 -51.2 -15.2  16.8  36.8  40.8  83.8  95.8]
The dot product of weight vector and input vector:
-12214.399999999281
The final sum:
-12214.399999999281
The weight vector 

In [86]:
a = [[1,2,3,4],[1,2],[3,4,5],[6,7]]
b = a[2:]
c = a[:3]
print(b)
print(c)
x = float()
x = 5
print("Python is fun",x)

[[3, 4, 5], [6, 7]]
[[1, 2, 3, 4], [1, 2], [3, 4, 5]]
Python is fun 5
